services:
  backend:
    build: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api/:/api/
    depends_on:
      - db

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 443:443
  #     - 80:80
  # admin-panel:
  #   build: ./admin-panel

  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USERNAME: dev
      POSTGRES_DB: dev
    volumes:
      - ./data/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 10s
      timeout: 5s
      retries: 5

 