services:
  backend:
    build: ./api
    environment:
      DB_HOST: db
      DB_USER: ${POSTGRES_USERNAME}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB_NAME}
      DB_PORT: ${POSTGRES_DB_PORT}
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      ADMIN_EMAIL: ${DJANGO_ADMIN_EMAIL}
      ADMIN_USERNAME: ${DJANGO_ADMIN_USERNAME}
      ADMIN_PASSWORD: ${DJANGO_ADMIN_PASSWORD}
      DEV_MODE: FALSE
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
      args:
        - DEV_MODE=FALSE
    env_file:
      - ./.env
    ports:
      - 443:443
      - 80:80
    depends_on:
      - backend
      - admin-panel
    volumes:
      - /etc/letsencrypt/live/chipchop.mooo.com/:/etc/letsencrypt/live/chipchop.mooo.com/
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://backend:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  admin-panel:
    env_file:
      - ./.env
    build:
      context: ./admin-panel
      args:
        - DEV_MODE=FALSE
  db:
    image: postgres:17.0-alpine3.20
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_PORT: ${POSTGRES_DB_PORT}
    volumes:
      - ./data/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME}"]
      interval: 1s
      timeout: 1s
      retries: 10
