# Generated by Django 4.2.16 on 2024-10-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='cccook',
            options={'verbose_name_plural': 'Chip Chop Cooks'},
        ),
        migrations.AlterModelOptions(
            name='ccdelivery',
            options={'verbose_name_plural': 'Chip Chop Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='ccuser',
            options={'verbose_name_plural': 'Chip Chop Users'},
        ),
    ]
