# Generated by Django 4.2.16 on 2024-11-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccuser',
            name='age',
        ),
        migrations.AddField(
            model_name='ccuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
