# Generated by Django 4.2.16 on 2024-10-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccuser',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
