# Generated by Django 4.2.16 on 2024-10-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_ccuser_username_address_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
