# Generated by Django 4.2.16 on 2024-10-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ccuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccuser',
            name='role',
            field=models.CharField(choices=[('U', 'User'), ('C', 'Cook'), ('D', 'Delivery')], default='U', max_length=1),
        ),
    ]
