# Generated by Django 4.2.16 on 2024-10-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0004_cccook_alter_dish_user'),
        ('users', '0004_ccuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccdelivery',
            name='user',
        ),
        migrations.DeleteModel(
            name='CCCook',
        ),
        migrations.DeleteModel(
            name='CCDelivery',
        ),
    ]
