# Generated by Django 4.2.16 on 2024-10-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_ccdelivery_user_delete_cccook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccuser',
            name='role',
            field=models.CharField(choices=[('U', 'User'), ('C', 'Cook'), ('D', 'Deliverer')], default='U', max_length=1),
        ),
    ]
