# Generated by Django 4.2.16 on 2024-10-21 13:41

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_ccuser_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ccuser',
            managers=[
                ('objects', users.models.CCUserManager()),
            ],
        ),
    ]
