# Generated by Django 4.2.16 on 2024-10-08 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountupgradepetition',
            name='id',
        ),
        migrations.AlterField(
            model_name='accountupgradepetition',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
