# Generated by Django 4.2.16 on 2024-10-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_remove_accountupgradepetition_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountupgradepetition',
            name='state',
            field=models.TextField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P'),
        ),
    ]
