# Generated by Django 4.2.16 on 2024-10-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0003_accountupgradepetition_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountupgradepetition',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
