# Generated by Django 4.2.16 on 2024-10-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0004_alter_accountupgradepetition_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountupgradepetition',
            name='state',
            field=models.TextField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
