# Generated by Django 4.2.16 on 2024-11-12 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('D', 'Delivery'), ('P', 'Pickup')], default='P', max_length=1)),
                ('order_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('C', 'Cooking'), ('B', 'Burnt Kitchen'), ('K', 'Cooked'), ('D', 'Delivering'), ('T', 'Traffic Accident'), ('S', 'Atracao'), ('F', 'Finished')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(editable=False)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('amount', models.IntegerField(default=1)),
                ('note', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Order Dishes',
            },
        ),
    ]
