# Generated by Django 4.2.16 on 2024-10-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('D', 'Delivery'), ('P', 'Pickup')], default='P', editable=False, max_length=1),
        ),
    ]
