# Generated by Django 4.2.16 on 2024-10-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('C', 'Cooking'), ('B', 'Burnt Kitchen'), ('K', 'Cooked'), ('D', 'Delivering'), ('T', 'Traffic Accident'), ('S', 'Atracao'), ('F', 'Finished'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
