# Generated by Django 4.2.16 on 2024-10-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderdish',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 1), ('amount__lt', 1000)), name='Order Dish amount must be between 1 and 1000'),
        ),
    ]
