# Generated by Django 4.2.16 on 2024-10-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='last_update_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
