# Generated by Django 4.2.16 on 2024-10-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0002_alter_dish_last_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
