# Generated by Django 4.2.16 on 2024-10-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0005_alter_dish_discount_alter_dish_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
