# Generated by Django 4.2.16 on 2024-10-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0005_alter_dish_discount_alter_dish_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
