# Generated by Django 4.2.16 on 2024-10-28 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0006_dishcategory_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cooks.dishcategory'),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
