# Generated by Django 4.2.16 on 2024-10-30 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCDeliverer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('transport', models.CharField(choices=[('C', 'Car'), ('B', 'Bicycle'), ('S', 'Scooter')], default='C', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Chip Chop Deliverers',
            },
        ),
    ]
