# Generated by Django 4.2.16 on 2024-10-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccdeliverer',
            name='transport',
            field=models.CharField(choices=[('C', 'Car'), ('B', 'Bycicle'), ('S', 'Scooter')], default='C', max_length=1),
        ),
    ]
